os: linux
language: generic
dist: bionic
addons:                    
  apt:                     
    packages:              
      - python3-pip        
      - python3-setuptools 
env:
  matrix:
  - VERSION=18.0.5 VERSION_MAJOR=18 LATEST=true
  - VERSION=17.0.7 VERSION_MAJOR=17
  - VERSION=16.0.9 VERSION_MAJOR=16
before_install:
  # Configure environment so changes are picked up when the Docker daemon is restarted after upgrading
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  # Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker buildx create --name builder --use
  - docker buildx ls
  - sudo apt-get install -y pwgen
  - docker --version
  - docker-compose --version
  - |
    if docker pull tob123/nextcloud-ma:${VERSION}; then
      echo "docker pull is allowed to fail"
    fi
#  - docker-compose -f ./ac/docker-compose.yaml up -d
# docker pull does not speed things up for this build
#  - docker pull tob123/nextcloud-staging:${VERSION}
  - pip3 install --user anchorecli        
  - export PATH="$HOME/.local/bin/:$PATH" 
install:
  - export NC_PASS_CI=`pwgen -s -N1 20`
  - export DB_PASS_CI=`pwgen -s -N1 20`
  - export MYSQL_ROOT_PASSWORD_CI=`pwgen -s -N1 20`
  - echo "$DOCKER_HUB_P" | docker login --username "$DOCKER_HUB_U" --password-stdin
  - bash build_and_push.sh
  - docker-compose -f ./nc/docker-compose.test.yml up -d
  - docker container ls
  - docker inspect --format="{{json .State.Health.Status}}" nc_sut_1
  - |
    SUT_HEALTH="notok" && counter=0
    while [ $SUT_HEALTH != "healthy" ] && [ $counter -le 60 ]; do
    SUT_HEALTH=$(docker inspect --format="{{json .State.Health.Status}}" nc_sut_1 | tr -d '"')
    sleep 2
    counter=$(( $counter + 1 ))
    echo $counter
    if [ $counter -eq 60 ]; then
    echo $counter
    docker logs nc_sut_1
    exit 1
    fi
    done
  - docker inspect --format="{{json .State.Health.Status}}" nc_sut_1
  - docker logs nc_sut_1
  - docker container ls
  - docker image ls
script:
  - anchore-cli image add docker.io/tob123/nextcloud-ma-staging:${VERSION}     
  - anchore-cli image wait docker.io/tob123/nextcloud-ma-staging:${VERSION}    
  - anchore-cli evaluate check docker.io/tob123/nextcloud-ma-staging:${VERSION}
deploy:
  provider: script
  script: bash dockcompare.sh

