version: 2.1

orbs:
    anchore: anchore/anchore-engine@1.1.0

workflows:
    scan_image:
        jobs:
          - anchore/image_scan:
              image_name: 'docker.io/tob123/nextcloud-staging:15'
